const $ = s => document.querySelector(s);
const app = $('#app'); let current='home', selected=null, editing=false;
let memberStore=[], profileStore={};
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('MemberDiaryDB',1);r.onupgradeneeded=()=>{const db=r.result;db.createObjectStore('members');db.createObjectStore('settings')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
function readRecord(store,key){return dbPromise.then(db=>new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}))}
function writeRecord(store,key,value){return dbPromise.then(db=>new Promise((resolve,reject)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).put(value,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)}))}
const fields=[
['Personal Details',[['proposer','Name of Proposer','text',1],['insured','Name of Insured Person','text',1],['father','Father Name'],['mother','Mother Name'],['spouse','Spouse Name'],['child1','Child 1'],['child2','Child 2'],['child3','Child 3'],['address','Full Address','textarea'],['dob','Date of Birth','date'],['height','Height'],['weight','Weight'],['occupation','Occupation'],['income','Annual Income']]],
['Contact & Identity Details',[['phone','Phone Number','tel',1],['email','Email ID','email'],['aadhaar','Aadhaar Card No'],['pan','PAN Card No']]],
['Plan / Premium Details',[['plan','Plan Name','text',1],['sumInsured','Sum Insured'],['premium','Model / Premium']]],
['Nominee Details',[['nominee','Nominee Name'],['nomineeAge','Nominee Age','number']]],
['Policy Details',[['doc','DOC','date'],['policy','Policy No','text',1],['customerId','Customer ID No'],['disease','Pre Existing Disease if any','textarea']]],
['Nominee Bank Details',[['bank','Bank Name'],['branch','Branch'],['accountType','Account Type','select'],['account','Account No'],['ifsc','IFSC Code']]]
];
const getMembers=()=>memberStore; const saveMembers=x=>{memberStore=x;writeRecord('members','all',x)};
const getProfile=()=>profileStore; const val=(x)=>x||'—';
function nav(page,id){current=page;selected=id||null;editing=false; render();window.scrollTo(0,0)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function header(){ $('.back').classList.toggle('visible',current!=='home'); $('.profile-button').style.visibility=current==='home'?'visible':'hidden'; }
function home(){return `<section class="page home"><div class="greeting"><h2>Welcome back.</h2><p>Your trusted space for member records and policy details.</p></div><div class="home-actions"><button class="action-card primary" onclick="nav('form')"><span class="action-icon">＋</span><span><strong>Add New Member</strong><small>Create a complete member record</small></span><span class="chevron">›</span></button><button class="action-card" onclick="nav('members')"><span class="action-icon">♙</span><span><strong>View Member Details</strong><small>Search and manage all records</small></span><span class="chevron">›</span></button></div><p class="privacy-note">Member information is private and securely kept on this device.</p></section>`}
function input(f,d={}){let [key,label,type='text',req]=f, v=d[key]||'', r=req?'<span class="required"> *</span>':''; if(type==='textarea')return `<div class="field"><label>${label}${r}</label><textarea name="${key}" ${req?'required':''}>${v}</textarea></div>`;if(type==='select')return `<div class="field"><label>${label}</label><select name="${key}"><option value="">Select account type</option>${['Savings','Current','Other'].map(x=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}${r}</label><input name="${key}" type="${type}" value="${v}" ${req?'required':''}></div>`}
function form(){let d=editing?getMembers().find(x=>x.id===selected)||{}:{};return `<section class="page"><h2 class="page-title">${editing?'Edit Member':'Add New Member'}</h2><p class="subtitle">${editing?'Update the member record below.':'Complete the details section by section.'}</p><form id="member-form">${fields.map(([name,fs])=>`<section class="section"><div class="section-head">${name.toUpperCase()}</div><div class="section-body">${fs.map(f=>input(f,d)).join('')}</div></section>`).join('')}<div class="form-actions"><button class="button primary" type="submit">${editing?'Save Changes':'Save Member'}</button><button class="button secondary" type="button" onclick="historyBack()">Cancel</button></div></form></section>`}
function members(){let list=getMembers();return `<section class="page"><h2 class="page-title">Members</h2><p class="subtitle">Search and view member records</p><div class="search"><input id="search" oninput="filterMembers()" placeholder="Search name, phone, policy or customer ID"></div><div id="member-list">${cards(list)}</div></section>`}
function cards(list){if(!list.length)return `<div class="empty"><div class="empty-icon">⌕</div><strong>No members found</strong><p>Add a new member to begin.</p></div>`;return list.map(x=>`<button class="member-card" onclick="nav('details','${x.id}')"><h3>${val(x.proposer)}</h3><p>${val(x.insured)} · ${val(x.phone)}</p><div class="member-meta"><span>POLICY: ${val(x.policy)}</span><span>${val(x.plan)}</span></div></button>`).join('')}
function details(){let d=getMembers().find(x=>x.id===selected);if(!d){nav('members');return ''}return `<section class="page"><h2 class="page-title">Member Details</h2><p class="subtitle">Member ID: ${d.id}</p>${fields.map(([name,fs])=>`<section class="detail-section"><h3>${name.toUpperCase()}</h3><div class="detail-grid">${fs.map(([key,label])=>`<div class="detail-value ${key==='address'||key==='disease'?'wide':''}"><label>${label}</label><p>${val(d[key])}</p></div>`).join('')}</div></section>`).join('')}<div class="actions-row"><button class="button secondary" onclick="editMember()">Edit Member</button><button class="button danger" onclick="confirmDelete()">Delete Member</button></div></section>`}
function profile(){let d=getProfile();return `<section class="page"><h2 class="page-title">Profile</h2><p class="subtitle">Agent and SSM information</p><div class="profile-card"><span class="eyebrow">MEMBER DIARY</span><strong>${val(d.agentName)}</strong><p>${d.agentCode?'Agent Code: '+d.agentCode:'Set up your agent profile'}</p></div><form id="profile-form"><section class="section"><div class="section-head">AGENT DETAILS</div><div class="section-body">${input(['agentName','Agent Name'],d)}${input(['agentCode','Agent Code'],d)}</div></section><section class="section"><div class="section-head">SSM DETAILS</div><div class="section-body">${input(['ssmName','SSM Name'],d)}${input(['ssmCode','SSM Code'],d)}</div></section><button class="button primary" type="submit">Save Profile</button></form></section>`}
function render(){header();app.innerHTML=current==='home'?home():current==='form'?form():current==='members'?members():current==='details'?details():profile(); if(current==='form')$('#member-form').onsubmit=saveForm;if(current==='profile')$('#profile-form').onsubmit=saveProfile}
function saveForm(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(!/^\+?[0-9 ()-]{7,20}$/.test(d.phone)){toast('Enter a valid phone number.');return}if(d.email&&!/^\S+@\S+\.\S+$/.test(d.email)){toast('Enter a valid email address.');return}let all=getMembers();if(editing){let i=all.findIndex(x=>x.id===selected);all[i]={...all[i],...d};saveMembers(all);toast('Member details updated successfully.');nav('details',selected)}else{let id='MD-'+Date.now().toString(36).toUpperCase();all.unshift({id,...d});saveMembers(all);toast('Member added successfully.');nav('details',id)}}
function saveProfile(e){e.preventDefault();profileStore=Object.fromEntries(new FormData(e.target));writeRecord('settings','profile',profileStore);toast('Profile saved successfully.');nav('home')}
function filterMembers(){let q=$('#search').value.toLowerCase();$('#member-list').innerHTML=cards(getMembers().filter(x=>[x.proposer,x.insured,x.phone,x.policy,x.customerId].some(v=>(v||'').toLowerCase().includes(q))))}function editMember(){editing=true;current='form';render();window.scrollTo(0,0)}function historyBack(){nav(current==='form'&&editing?'details':'home',editing?selected:null)}function confirmDelete(){$('#modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Delete member?</h2><p>Are you sure you want to delete this member? This action cannot be undone.</p><div class="modal-actions"><button class="button secondary" onclick="closeModal()">Cancel</button><button class="button danger" onclick="deleteMember()">Delete</button></div></div></div>`}function closeModal(){$('#modal-root').innerHTML=''}function deleteMember(){saveMembers(getMembers().filter(x=>x.id!==selected));closeModal();toast('Member deleted successfully.');nav('members')}$('.back').onclick=historyBack;$('.profile-button').onclick=()=>nav('profile');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');dbPromise.then(async()=>{memberStore=await readRecord('members','all')||[];profileStore=await readRecord('settings','profile')||{};render()}).catch(()=>{toast('Local database could not be opened.');render()});
